# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eugene Kim
subtitle: Another Dev Blog
name: Eugene Kim
email: simplyeugene94@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Eugene Kim, a software developer. This is my blog 
  where I keep track of fun and interesting software projects that I have
  worked on throughout my career. Hopefully, you learn something new with me!
baseurl: "" # the subpath of your site, e.g. /blog
domain: ekim1394.github.io
url: https://ekim1394.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ekim1394
repository: ekim1394/ekim1394.github.io
search: true

# Pagination settings
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Default settings for posts, pages, and collections
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _foo
  - scope:
      path: ""
      type: foo
    values:
      layout: single

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
